swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get all the user's bank accounts
      description: API for fetching all the user's bank accounts
       #produces:
       # - application/json
      responses:
        '200':
          description: All the user's bank accounts retrieved successully
          schema:
            $ref: '#/definitions/Accounts'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/specificAccount:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get a specific bank account
      description: API for fetching a specific bank account
       #produces:
       # - application/json
      responses:
        '200':
          description: Specific bank account retrieved successully
          schema:
            $ref: '#/definitions/SpecificAccount'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error          
  /user/accounts/specificAccount/transactions:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get every transactions of a specific bank account
      description: API for fetching every transactions of a specific bank account
       #produces:
       # - application/json
      responses:
        '200':
          description: Each transactions of a specific account retrieved successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/specificAccount/transactions/specificTransaction:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get a specific transaction in a specific account
      description: API for fetching a specific transaction in a specific account
       #produces:
       # - application/json
      responses:
        '200':
          description: Specific transaction of a specific account retrieved successully
          schema:
            $ref: '#/definitions/SpecificTransaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    patch:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update or delete a specific information field of a specific transaction  
      description: API for updating or deleting a specific information field of a specific transaction
       #produces:
       # - application/json
      responses:
        '200':
          description: The specific information field retrieved successully
          schema:
            $ref: '#/definitions/UpdateTransactionInformations'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/specificAccount/transactions/monthId:
   post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get all transactions of a specific bank account for a specific month
      description: API for fetching all transactions of a specific bank account for a specific month
       #produces:
       # - application/json
      responses:
        '200':
          description: All the transactions of a specific bank account for a specific month retrieved successully
          schema:
            $ref: '#/definitions/MonthTransactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Accounts:
    type: object
    properties:
      accountsArrayId:
        type: string
  SpecificAccount:
    type: object
    properties:
      accountsArrayId:
        type: string
      specificAccountId:
        type: string
  Transactions:
    type: object
    properties:
      accountsArrayId:
        type: string
      specificAccountId:
        type: string
      transactionsArrayId:
        type: string
  SpecificTransaction:
    type: object
    properties:
      accountsArrayId:
        type: string
      specificAccountId:
        type: string
      transactionsArrayId:
        type: string
      specificTransactionId:
        type: string
  UpdateTransactionInformations:
    type: object
    properties:
      accountsArrayId:
        type: string
      specificAccountId:
        type: string  
      transactionsArrayId:
        type: string
      specificTransactionId:
        type: string
      valueLocation:
        type: string
      newTxtValue: 
       type: string
  MonthTransactions:
    type: object
    properties:
      accountsArrayId:
        type: string
      specificAccountId:
        type: string
      transactionsArrayId:
        type: string
      monthId:
        type: string