swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/accounts:
    post:
      security:
        - Bearer: []
      tags:
        - Financial Data
      summary: A concise recap of the user's each account
      description: API for getting a brief summary of each account to put on the profile page
      responses:
        '200':
          description: A recap of every account retrieved successfully
          schema:
            $ref: "#/definitions/AccountsSummary"
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/accounts/{accountId}/transactions_{currentMonthId}:  
    parameters:
        - in: path
          name: accountId
          description: Account ID
          required: true
          type: integer
        - in: path
          name: currentMonthId
          description: Current month ID
          required: true
          type: integer          
    post:
      security:
        - Bearer: []
      tags:
        - Financial Data
      summary: A summary of every transactions of a specific account for the current month
      description: API for getting a summary of all transactions of a specific account for a limited period of time (the current month)
      responses:
        '200':
          description: All the current month's transactions of this specific account retrieved successfully
          schema:
            $ref: "#/definitions/TransactionsSummary"
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/accounts/{accountId}/transactions/{transactionId}:
    parameters:
        - in: path
          name: accountId
          description: Account ID
          required: true
          type: integer
        - in: path
          name: transactionId
          description: Transaction ID
          required: true
          type: integer  
    post:
      security:
        - Bearer: []
      tags:
        - Financial Data
      summary: Details about a specific transaction  
      description: API for getting all available details about a specific transaction
      responses:
        '200':
          description: All the details about this specific transaction retrieved successfully
          schema:
            $ref: "#/definitions/TransactionDetails"
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/accounts/{accountId}/transactions/{transactionId}/{fieldToModify}: 
    parameters:
        - in: path
          name: accountId
          description: Account ID
          required: true
          type: integer
        - in: path
          name: transactionId
          description: Transaction ID
          required: true
          type: integer
        - in: path
          name: fieldToModify
          description: ID of the field to modify
          required: true
          type: string
    post:
      security:
        - Bearer: []
      tags:
        - Financial Data Modifications
      summary: Add data to a transaction
      description: API for adding data to a specific field of a specific transaction
      responses:
        '200':
          description: The data was successfully added to the transaction
          schema:
            $ref: "#/definitions/AddData"
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Financial Data Modifications
      summary: Update a transaction's data
      description: API for updating data on a specific field of a specific transaction
      responses:
        '200':
          description: The field was successfully updated
          schema:
            $ref: "#/definitions/UpdateData"
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error  
    delete:
      security:
        - Bearer: []
      tags:
        - Financial Data Modifications
      summary: Delete a transaction's data
      description: API for deleting data on a specific field of a specific transaction
      responses:
        '200':
          description: The data was successfully deleted
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error      
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string       
  AccountsSummary:
    type: object
    properties:
      accountName:
        type: string
      accountId:
        type: integer
      balance:
        type: number
      balanceDescription:
        type: string
  TransactionsSummary:
    type: object
    properties:
      transactionDate:
        type: string
        format: date
      transactionDescription:
        type: string
      transactionAmount:
        type: number
      transactionBalance:
        type: number  
  TransactionDetails:
    type: object
    properties:
      transactionType: 
        type: string
      categoryTxtValue:
        type: string
      notesTxtValue:
        type: string
  AddData:
    type: object
    properties:
      addedValue:
        type: string 
  UpdateData:
    type: object
    properties:
      updatedTxtValue:
        type: string